name: Notify Assignee by Email

on:
  issues:
    types: [assigned]

jobs:
  send-email:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install jq (if necessary)
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      - name: Extract Assignee Email
        id: extract_email
        run: |
          EMAIL_MAPPING='${{ secrets.USER_EMAIL_MAPPING }}'
          ASSIGNEE="${{ github.event.issue.assignee.login }}"
          EMAIL=$(echo "$EMAIL_MAPPING" | jq -r --arg assignee "$ASSIGNEE" '.[$assignee]')
          if [ "$EMAIL" == "null" ]; then
            echo "Assignee email not found."
            exit 1
          fi
          echo "assignee_email=$EMAIL" >> $GITHUB_ENV

      - name: Get Assignee Email
        id: get_mail
        # 先取得 assignee 的名稱
        # 接著使用 github 的 API，請求它的 email 資訊
        # 但是有些人會把 email 設定成 private，因此可能為 null
        run: |
          ASSIGNEE="${{ github.event.issue.assignee.login }}"
          RESPONSE=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                         -H "Accept: application/vnd.github.v3+json" \
                         https://api.github.com/users/$ASSIGNEE)
                         
          EMAIL=$(echo "$RESPONSE" | jq -r '.email')
          
          if [ -z "$EMAIL" ] || [ "$EMAIL" == "null" ]; then
            echo "Email not found for assignee $ASSIGNEE."
          else
            echo "Found email for assignee: $EMAIL"
          fi
          
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Send Email
        run: |
          python send_email.py "$assignee_email" \
            "Issue Assigned: ${{ github.event.issue.title }}" \
            "You have been assigned to the issue: ${{ github.event.issue.html_url }}"
        env:
          SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
