name: Notify Assignee by Email

on:
  issues:
    types: [assigned]

jobs:
  send-email:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Extract Assignee Email
        id: extract_email
        run: |
          EMAIL_MAPPING="${{ secrets.USER_EMAIL_MAPPING }}"
          ASSIGNEE="${{ github.event.issue.assignee.login }}"
          EMAIL=$(echo "$EMAIL_MAPPING" | jq -r --arg assignee "$ASSIGNEE" '.[$assignee]')
          if [ "$EMAIL" == "null" ]; then
            echo "Assignee email not found."
            exit 1
          fi
          echo "::set-output name=assignee_email::$EMAIL"

      - name: Send Email
        run: |
          python send_email.py "${{ steps.extract_email.outputs.assignee_email }}" \
            "Issue Assigned: ${{ github.event.issue.title }}" \
            "You have been assigned to the issue: ${{ github.event.issue.html_url }}"
        env:
          SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
